name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there!
        MSG: I'm checking your code...
      run: echo $MY_VAR $MSG
      
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Run code
      run: g++ Source.cpp
